export default [
  {
    id: 1,
    make: 'Jaguar',
    model: 'XK Series',
    color: 'Goldenrod',
    year: 1997,
  },
  {
    id: 2,
    make: 'Toyota',
    model: 'RAV4',
    color: 'Purple',
    year: 2006,
  },
  {
    id: 3,
    make: 'Volvo',
    model: 'V70',
    color: 'Purple',
    year: 2008,
  },
  {
    id: 4,
    make: 'Lexus',
    model: 'GS',
    color: 'Teal',
    year: 2005,
  },
  {
    id: 5,
    make: 'Mercedes-Benz',
    model: 'CL-Class',
    color: 'Khaki',
    year: 2005,
  },
  {
    id: 6,
    make: 'Dodge',
    model: 'Journey',
    color: 'Goldenrod',
    year: 2011,
  },
  {
    id: 7,
    make: 'Mitsubishi',
    model: 'Truck',
    color: 'Crimson',
    year: 1993,
  },
  {
    id: 8,
    make: 'Ford',
    model: 'Thunderbird',
    color: 'Puce',
    year: 1965,
  },
  {
    id: 9,
    make: 'Jaguar',
    model: 'XJ',
    color: 'Blue',
    year: 2010,
  },
  {
    id: 10,
    make: 'Subaru',
    model: 'SVX',
    color: 'Yellow',
    year: 1997,
  },
  {
    id: 11,
    make: 'Hyundai',
    model: 'Sonata',
    color: 'Aquamarine',
    year: 1998,
  },
  {
    id: 12,
    make: 'Buick',
    model: 'Park Avenue',
    color: 'Violet',
    year: 2001,
  },
  {
    id: 13,
    make: 'Geo',
    model: 'Prizm',
    color: 'Orange',
    year: 1993,
  },
  {
    id: 14,
    make: 'Audi',
    model: '90',
    color: 'Crimson',
    year: 1995,
  },
  {
    id: 15,
    make: 'Dodge',
    model: 'Ram Van 3500',
    color: 'Goldenrod',
    year: 1999,
  },
  {
    id: 16,
    make: 'Maserati',
    model: 'Spyder',
    color: 'Blue',
    year: 2004,
  },
  {
    id: 17,
    make: 'Volvo',
    model: 'S80',
    color: 'Violet',
    year: 1999,
  },
  {
    id: 18,
    make: 'Toyota',
    model: 'Sienna',
    color: 'Red',
    year: 1999,
  },
  {
    id: 19,
    make: 'Cadillac',
    model: 'Fleetwood',
    color: 'Purple',
    year: 1994,
  },
  {
    id: 20,
    make: 'Chevrolet',
    model: 'S10',
    color: 'Indigo',
    year: 1993,
  },
  {
    id: 21,
    make: 'Ford',
    model: 'Crown Victoria',
    color: 'Goldenrod',
    year: 2003,
  },
  {
    id: 22,
    make: 'Pontiac',
    model: 'Grand Prix',
    color: 'Puce',
    year: 1990,
  },
  {
    id: 23,
    make: 'Subaru',
    model: 'Outback',
    color: 'Crimson',
    year: 2008,
  },
  {
    id: 24,
    make: 'Lexus',
    model: 'IS F',
    color: 'Crimson',
    year: 2011,
  },
  {
    id: 25,
    make: 'Toyota',
    model: 'T100 Xtra',
    color: 'Goldenrod',
    year: 1997,
  },
  {
    id: 26,
    make: 'Buick',
    model: 'Park Avenue',
    color: 'Maroon',
    year: 1995,
  },
  {
    id: 27,
    make: 'Mitsubishi',
    model: 'Eclipse',
    color: 'Khaki',
    year: 1989,
  },
  {
    id: 28,
    make: 'Suzuki',
    model: 'Daewoo Lacetti',
    color: 'Orange',
    year: 2006,
  },
  {
    id: 29,
    make: 'Hyundai',
    model: 'Genesis',
    color: 'Indigo',
    year: 2010,
  },
  {
    id: 30,
    make: 'Oldsmobile',
    model: 'Achieva',
    color: 'Red',
    year: 1996,
  },
  {
    id: 31,
    make: 'Buick',
    model: 'Century',
    color: 'Khaki',
    year: 1987,
  },
  {
    id: 32,
    make: 'Jensen',
    model: 'Interceptor',
    color: 'Crimson',
    year: 1966,
  },
  {
    id: 33,
    make: 'Hyundai',
    model: 'Tucson',
    color: 'Green',
    year: 2010,
  },
  {
    id: 34,
    make: 'Smart',
    model: 'Fortwo',
    color: 'Goldenrod',
    year: 2009,
  },
  {
    id: 35,
    make: 'Nissan',
    model: 'Altima',
    color: 'Fuscia',
    year: 2013,
  },
  {
    id: 36,
    make: 'Toyota',
    model: 'Xtra',
    color: 'Yellow',
    year: 1994,
  },
  {
    id: 37,
    make: 'Chevrolet',
    model: 'Tahoe',
    color: 'Purple',
    year: 2013,
  },
  {
    id: 38,
    make: 'Daihatsu',
    model: 'Rocky',
    color: 'Aquamarine',
    year: 1992,
  },
  {
    id: 39,
    make: 'Mazda',
    model: 'Mazda6',
    color: 'Blue',
    year: 2007,
  },
  {
    id: 40,
    make: 'Buick',
    model: 'Park Avenue',
    color: 'Aquamarine',
    year: 2004,
  },
  {
    id: 41,
    make: 'Jaguar',
    model: 'XJ Series',
    color: 'Fuscia',
    year: 1994,
  },
  {
    id: 42,
    make: 'Jeep',
    model: 'Wrangler',
    color: 'Khaki',
    year: 1997,
  },
  {
    id: 43,
    make: 'Audi',
    model: 'S8',
    color: 'Orange',
    year: 2008,
  },
  {
    id: 44,
    make: 'Ford',
    model: 'Thunderbird',
    color: 'Orange',
    year: 2005,
  },
  {
    id: 45,
    make: 'Volkswagen',
    model: 'Passat',
    color: 'Crimson',
    year: 2002,
  },
  {
    id: 46,
    make: 'Saturn',
    model: 'S-Series',
    color: 'Maroon',
    year: 1998,
  },
  {
    id: 47,
    make: 'Lexus',
    model: 'ES',
    color: 'Indigo',
    year: 2011,
  },
  {
    id: 48,
    make: 'Porsche',
    model: 'Carrera GT',
    color: 'Teal',
    year: 2004,
  },
  {
    id: 49,
    make: 'Suzuki',
    model: 'X-90',
    color: 'Pink',
    year: 1996,
  },
  {
    id: 50,
    make: 'Dodge',
    model: 'Ram 2500',
    color: 'Maroon',
    year: 2001,
  },
  {
    id: 51,
    make: 'Acura',
    model: 'Legend',
    color: 'Aquamarine',
    year: 1990,
  },
  {
    id: 52,
    make: 'Subaru',
    model: 'Forester',
    color: 'Crimson',
    year: 1999,
  },
  {
    id: 53,
    make: 'Honda',
    model: 'CR-V',
    color: 'Khaki',
    year: 2009,
  },
  {
    id: 54,
    make: 'Buick',
    model: 'Enclave',
    color: 'Puce',
    year: 2010,
  },
  {
    id: 55,
    make: 'BMW',
    model: 'X5 M',
    color: 'Puce',
    year: 2010,
  },
  {
    id: 56,
    make: 'Ford',
    model: 'Econoline E250',
    color: 'Purple',
    year: 1995,
  },
  {
    id: 57,
    make: 'Mitsubishi',
    model: 'Galant',
    color: 'Purple',
    year: 2012,
  },
  {
    id: 58,
    make: 'Cadillac',
    model: 'Eldorado',
    color: 'Violet',
    year: 1999,
  },
  {
    id: 59,
    make: 'Ford',
    model: 'Focus ST',
    color: 'Violet',
    year: 2013,
  },
  {
    id: 60,
    make: 'Kia',
    model: 'Soul',
    color: 'Pink',
    year: 2011,
  },
  {
    id: 61,
    make: 'Jaguar',
    model: 'XK Series',
    color: 'Aquamarine',
    year: 2004,
  },
  {
    id: 62,
    make: 'Lotus',
    model: 'Esprit',
    color: 'Crimson',
    year: 1986,
  },
  {
    id: 63,
    make: 'Jaguar',
    model: 'XJ Series',
    color: 'Maroon',
    year: 1997,
  },
  {
    id: 64,
    make: 'Cadillac',
    model: 'XLR-V',
    color: 'Turquoise',
    year: 2009,
  },
  {
    id: 65,
    make: 'Ford',
    model: 'E250',
    color: 'Crimson',
    year: 1984,
  },
  {
    id: 66,
    make: 'Honda',
    model: 'Pilot',
    color: 'Yellow',
    year: 2007,
  },
  {
    id: 67,
    make: 'BMW',
    model: 'M3',
    color: 'Violet',
    year: 2011,
  },
  {
    id: 68,
    make: 'Nissan',
    model: 'Versa',
    color: 'Puce',
    year: 2007,
  },
  {
    id: 69,
    make: 'Ford',
    model: 'E350',
    color: 'Turquoise',
    year: 2004,
  },
  {
    id: 70,
    make: 'Dodge',
    model: 'Ram 1500',
    color: 'Mauv',
    year: 2002,
  },
  {
    id: 71,
    make: 'Toyota',
    model: '4Runner',
    color: 'Green',
    year: 2009,
  },
  {
    id: 72,
    make: 'Chevrolet',
    model: 'Corvette',
    color: 'Blue',
    year: 1972,
  },
  {
    id: 73,
    make: 'Dodge',
    model: 'Stealth',
    color: 'Aquamarine',
    year: 1995,
  },
  {
    id: 74,
    make: 'Maserati',
    model: 'Biturbo',
    color: 'Violet',
    year: 1987,
  },
  {
    id: 75,
    make: 'Nissan',
    model: 'Xterra',
    color: 'Violet',
    year: 2004,
  },
  {
    id: 76,
    make: 'Chevrolet',
    model: 'S10',
    color: 'Goldenrod',
    year: 1993,
  },
  {
    id: 77,
    make: 'Ford',
    model: 'Flex',
    color: 'Puce',
    year: 2012,
  },
  {
    id: 78,
    make: 'Mercedes-Benz',
    model: 'SLK-Class',
    color: 'Red',
    year: 2006,
  },
  {
    id: 79,
    make: 'Mazda',
    model: 'Tribute',
    color: 'Goldenrod',
    year: 2003,
  },
  {
    id: 80,
    make: 'Lexus',
    model: 'LS',
    color: 'Aquamarine',
    year: 2012,
  },
  {
    id: 81,
    make: 'Bentley',
    model: 'Continental',
    color: 'Green',
    year: 2007,
  },
  {
    id: 82,
    make: 'GMC',
    model: 'Yukon',
    color: 'Orange',
    year: 2001,
  },
  {
    id: 83,
    make: 'Mercury',
    model: 'Cougar',
    color: 'Aquamarine',
    year: 2002,
  },
  {
    id: 84,
    make: 'BMW',
    model: 'X3',
    color: 'Purple',
    year: 2012,
  },
  {
    id: 85,
    make: 'Mazda',
    model: 'Protege5',
    color: 'Blue',
    year: 2003,
  },
  {
    id: 86,
    make: 'Saturn',
    model: 'S-Series',
    color: 'Puce',
    year: 1999,
  },
  {
    id: 87,
    make: 'Lamborghini',
    model: 'Gallardo',
    color: 'Fuscia',
    year: 2005,
  },
  {
    id: 88,
    make: 'Ford',
    model: 'Explorer',
    color: 'Turquoise',
    year: 2003,
  },
  {
    id: 89,
    make: 'Dodge',
    model: 'Ram Van 3500',
    color: 'Orange',
    year: 1999,
  },
  {
    id: 90,
    make: 'Saturn',
    model: 'S-Series',
    color: 'Green',
    year: 1996,
  },
  {
    id: 91,
    make: 'Toyota',
    model: 'Corolla',
    color: 'Orange',
    year: 1999,
  },
  {
    id: 92,
    make: 'Mercedes-Benz',
    model: '500SEL',
    color: 'Indigo',
    year: 1993,
  },
  {
    id: 93,
    make: 'Infiniti',
    model: 'G37',
    color: 'Mauv',
    year: 2010,
  },
  {
    id: 94,
    make: 'Toyota',
    model: 'Tercel',
    color: 'Maroon',
    year: 1997,
  },
  {
    id: 95,
    make: 'Chevrolet',
    model: 'Tracker',
    color: 'Maroon',
    year: 2001,
  },
  {
    id: 96,
    make: 'Suzuki',
    model: 'Daewoo Magnus',
    color: 'Indigo',
    year: 2004,
  },
  {
    id: 97,
    make: 'Honda',
    model: 'CR-V',
    color: 'Khaki',
    year: 2009,
  },
  {
    id: 98,
    make: 'Suzuki',
    model: 'Samurai',
    color: 'Maroon',
    year: 1993,
  },
  {
    id: 99,
    make: 'Lincoln',
    model: 'MKS',
    color: 'Violet',
    year: 2013,
  },
  {
    id: 100,
    make: 'Honda',
    model: 'Civic',
    color: 'Indigo',
    year: 1988,
  },
];
